### ISSUE TITLE
Default options for seneca & catbox for seneca instead of lru-cache

### ISSUE THREAD

**Issue by ooogway** [hapijs/chairo#19]
Seneca uses lru-cache module for caching, which is an in-memory cache. When we integrate with hapi using chairo, certain use cases might require use of common cache infrastructure (for example redis, instead of in-memory).

Not sure if this is the correct forum for this, but if there was an option to use catbox (and appropriate adapter) instead of default lru-cache, it can solve this problem. 

Since this is a big ask, can we for now set default options for seneca in chairo and disable seneca caching by default, since [by default, seneca enables lru-cache](https://github.com/senecajs/seneca/blob/35f6a304f9d6fb5ac13b52c993c18fd57634ce03/seneca.js#L116-L119)?

https://github.com/hapijs/chairo/blob/master/lib/index.js#L20

```js
var defaults = {
	"log": "silent",
	"actcache": {
		"active": false
	}
};

var settings = Hoek.applyToDefaults(defaults, options);
var seneca = Seneca(settings);
```

**Comment by ooogway** [comment]
can I submit a PR for default seneca options ?

**Comment by geek** [comment]
@ooogway absolutely... the request means I will accept it, just that I am not making it a priority on my side to implement myself.

**Comment by ooogway** [comment]
can I submit a PR to seneca to replace lru-cache with catbox and catbox-memory (default)?

**Comment by geek** [comment]
@ooogway you are on a roll today, thanks for the help.  Yes, please do, I will add it to the next minor version

**Comment by geek** [comment]
Fixed by https://github.com/hapijs/chairo/pull/35
