### ISSUE TITLE
Role as client/server

### ISSUE THREAD

**Issue by mtharrison** [hapijs/chairo#2]
I struggled with Seneca the first time I looked into it. The thing that really blew me away though is when I split my actions into another process and everything just worked magically with a couple of lines of extra code. It might be good to include an example of this in the readme, just in case people coming from hapi rather than Seneca don't get this.

If I've understood Chairo correctly, it's intended for hapi/chairo to be at the front of the stack receiving API/website requests from consumers and then proxying to other Seneca microservices (which may or may not be also running hapi).

Perhaps the example from the readme could be split into 2 processes to show this:

**service.js (standalone no hapi)**

    var seneca = require('seneca')();

    // set up a few Seneca actions

    seneca.add({ lookup: 'date' }, function (message, next) {

        return next(null, { date: (new Date()).toString() });
    });

    seneca.add({ load: 'user' }, function (message, next) {

        return next(null, { name: message.name });
    });

    seneca.listen();    // Make a server

**index.js (hapi app)**

    ...
    server.register(Chairo, function (err) {

        server.seneca.client(); // Make a client so we can use remote actions

        // Set up a hapi view engine

        server.views({
            engines: { html: Handlebars },
            path: __dirname + '/templates'
        });
        ...

**Comment by AdriVanHoudt** [comment]
I assumed that when using the server methods the client and listen thing would happen automagicly?

**Comment by hueniverse** [comment]
We can add that as another step, in addition to the stuff already there. I'll take a PR.
