### ISSUE TITLE
how to mount jsonrest-api?

### ISSUE THREAD

**Issue by AdrieanKhisbe** [hapijs/chairo#28]
I would like to expose a seneca data entity with [jsonrest-api](https://www.npmjs.com/package/seneca-jsonrest-api)

[Examples are using express](https://github.com/rjrodger/seneca-examples/blob/master/api-server/app.js#L3-L15)
and I didn't find anything related to this in the chairo README

**Comment by geek** [comment]
At the moment we don't have a jsonrest-api implementation for hapi+chairo.  However, you can use the seneca instance from chairo to follow the example you linked to:

```js
server.seneca.use('./product_catalog')
      .use('./api')
      .ready(function(){
        this.make$('product')
          .make$({id$:0,name:'Apple',price:99,star:0}).save$()
          .make$({id$:1,name:'Orange',price:199,star:0}).save$()
      })
```

Is the goal to be able to create a specification and have it generate the API endpoints and use seneca entities on the backend?

**Comment by AdrieanKhisbe** [comment]
yep, the point is to expose a *seneca-data-entity* as a rest api (in Hapi).

In fact it's more this part i'm interested in : 
```js
var app = require('express')()
      .use( require('body-parser').json() )
      .use( seneca.export('web') )
      .listen(3000)
```
 
:)

**Comment by AdrieanKhisbe** [comment]
@geek Would be interested to help implement it, even more if you drive me through it :)

(_ps contacted you throught gitter_)

**Comment by seanrucker** [comment]
@AdrieanKhisbe I've been thinking of a similar project. Are you using Ember per chance?

**Comment by AdrieanKhisbe** [comment]
@seanrucker  Nope, we are using react.js at the company I'm working at.

**Comment by geek** [comment]
@AdrieanKhisbe that would be really helpful, we definitely need something like that. Feel free to reach me on gitter and we can discuss.  Thanks!

**Comment by AdrieanKhisbe** [comment]
@geek :)
shall we create a hapijs/seneca room on gitter then?

**Comment by geek** [comment]
I would rather not, instead I will monitor hapi and seneca rooms... at least until chairo takes off more :)

**Comment by AdrieanKhisbe** [comment]
okey dokey, no problem!
better on seneca then?
(hapi more activity)

**Comment by geek** [comment]
@AdrieanKhisbe ya, I think the seneca gitter makes more sense for this

**Comment by AdrieanKhisbe** [comment]
@geek, 
I'll trigger the disucssion tomorrow morning, the wednesday then :)
