### ISSUE TITLE
The future of Hapi and Seneca

### ISSUE THREAD

**Issue by seanrucker** [hapijs/chairo#3]
I was looking for a solution to organize my business logic into microservices. I was already using Hapi and organizing my code into Hapi server methods so this plugin fit the bill nicely. 

Chairo was my introduction to Seneca. I've been trying to get up and running with Seneca but finding lots of holes in the documentation and fairly significant bugs. I'm wondering if this Hapi integration is a first step towards Seneca getting better supported/contributed to. 

Is the Hapi team using Seneca in production? Is there any established relationship between the Hapi core team and the Seneca core team (Rodger)? 

I'm on the verge of looking for an alternative, but will muscle through with Seneca if the future of Hapi/Seneca integration looks bright.

**Comment by hueniverse** [comment]
First, there is no "hapi team" in the sense of a team working for one company. hapi contributors come from dozens of companies and projects.

Seneca is used in production by nearForm and while there are areas of it that are not fully mature, the core functionality exposed by this plugin is pretty stable.@rjrodger can offer you more information about documentation and how it is being used.

There is interesting work coming to make the two framework work better together. I am not sure on ETA.
