### ISSUE TITLE
Difference between server methods and Seneca actions?

### ISSUE THREAD

**Issue by SteffenGorenflo** [hapijs/chairo#4]
I'm not quite sure if I understand this correctly, but I don't see much difference between a seneca action and a server method besides a different notation.

Sure, chairo connects the Seneca framework but the implementation of the actions (as in the examples) are still in the hapi server process and not really different than global server methods. 

Am I missing something? Or how it is possible to implement actions outside of hapi?

**Comment by mtharrison** [comment]
I think they're only shown in the same process in the README for brevity.

You can implement the actions on other services running on other processes or other servers (connected by seneca). And seneca will figure out how to communicate between your services. 

Have a look at my issue #2 for more info.

**Comment by hueniverse** [comment]
There is only so much we can show in the readme... @mtharrison's explanation is spot on.
