### ISSUE TITLE
How can I access seneca actions from other services? 

### ISSUE THREAD

**Issue by themauveavenger** [hapijs/chairo#45]
After creating Seneca actions, is it possible to access them from another service and not through the api created through hapi? What port are all of the actions exposed on? Do I need to go through the http api defined in a route?

**Comment by geek** [comment]
@themauveavenger it will depend on if your seneca instance has called `listen()` for a specific transport.  

You can definitely access them directly with TCP without using seneca as a client.  Here is an example of what the messages should look like that you send:

https://github.com/senecajs/seneca/issues/394#issuecomment-206993629
