### ISSUE TITLE
support seneca 2.0

### ISSUE THREAD

**Issue by bnusunny** [hapijs/chairo#46]
seneca 2.0 is released for sometime. It would be great to support for that version.

**Comment by geek** [comment]
I will update to support 2.0 directly.  However, you can install seneca 2.0.0 and use it with chairo, I added a `seneca` option to chairo that accepts an instance of seneca to use.

https://github.com/hapijs/chairo#plugin-registration

**Comment by bnusunny** [comment]
thanks for the quick feedback. I see the change in 2.2.0. But seneca 2.0 removed the seneca entity package as default dependency. Can you add seneca-entity as dependency in chairo?

**Comment by bnusunny** [comment]
never mind. I figured it out. We can require seneca-entity package and use it like below. 

```
server.seneca
      .use('entity')
```

**Comment by Wardormeur** [comment]
Stepped on the same issue, adding it to the doc/README would be great imho :)
