### ISSUE TITLE
If using external seneca then seneca-web is not set correctly with Hapi server instance

### ISSUE THREAD

**Issue by mirceaalexandru** [hapijs/chairo#48]
Due to this line:

https://github.com/hapijs/chairo/blob/master/lib/index.js#L59

if using external seneca then no end-point is registered into Hapi, as Hapi server instance is not set in the seneca-web

**Comment by mirceaalexandru** [comment]
Also seems that seneca.ready:

https://github.com/hapijs/chairo/blob/master/lib/index.js#L60

is not executed if external seneca is provided.

**Comment by geek** [comment]
@mirceaalexandru can you confirm if this is still an issue now that seneca-web is removed
