### ISSUE TITLE
Chairo/Seneca eating errors when testing

### ISSUE THREAD

**Issue by tribou** [hapijs/chairo#55]
I'm having trouble writing test cases for Chairo/Seneca that display specific errors without timing out.  Given the following test case (currently using `lab`, but also tried with `tape`):

```js
describe('getUser', () => {

  it('returns a Boom 404 error if no user is found', (done) => {

    const server = new Hapi.Server()
    server.connection()
    server.register([Chairo, TestDatabase, GetUserPlugin], (error) => {

      expect(error).to.not.exist()

      server.seneca.act({
        role: 'user',
        cmd: 'getUser',
        email: 'NotFound@email.com',
      }, (err, result) => {

        expect(err.isBoom).to.be.true()
        expect(err.output.statusCode).to.equal(404)
        done()

      })

    })

  })

})
```

This test as-is works successfully.  However, if I change any expectation to "break" it, `lab` will throw a timed out error instead of showing the details of which expectation failed.  

For example, changing the second expectation to:

```js
expect(err.isBoom).to.be.false()
```

Produces:

```
Failed tests:

  5) getUser returns a Boom 404 error if no user is found:

      Timed out (2000ms) - getUser returns a Boom 404 error if no user is found
```

I've tried increasing the test timeout to 15 seconds or so, and it still times out.  This also happens with multiple test cases which is why I wasn't sure if this was an issue with Chairo, Seneca, or Lab; and I'll be glad to repost if needed.

versons:
Node v4 and v6.6.0
lab 11.0.1
chairo 2.2.1

**Comment by geek** [comment]
@tribou are you able to reproduce the issue outside of the act handler or server register function?

**Comment by tribou** [comment]
@geek Thanks for the quick response!  It appears to go away if the assertions are outside of the seneca act handler.

Got a full example here:
```js
// healthCheck.js

// plugin
const healthCheckPlugin = (server, options, next) => {

  server.dependency('chairo')
  server.seneca
  .add({ role: 'upload', cmd: 'healthCheck' }, (message, done) => {

    return done(null, { ready: true })

  })
  next()

}

healthCheckPlugin.attributes = {
  name: 'healthCheck',
  version: '1.0.0',
}


module.exports = healthCheckPlugin
```

Test file:
```js
'use strict'

// Load modules
const Chairo = require('chairo')
const Code = require('code')
const Hapi = require('hapi')
const Lab = require('lab')

// Test shortcuts
const lab = exports.lab = Lab.script()
const describe = lab.describe
const it = lab.it
const expect = Code.expect

// SUT
const HealthCheckPlugin = require('./healthCheck.js')


describe('healthCheck', () => {


  it('registers as a Hapi plugin without error', (done) => {

    const server = new Hapi.Server()
    server.connection()
    server.register([Chairo, HealthCheckPlugin], (error) => {

      expect(error).to.not.exist()

      const serverPlugins = Object.keys(server.registrations)
      expect(serverPlugins).to.contain('healthCheck')
      done()

    })

  })


  it('returns ready:true', (done) => {

    const server = new Hapi.Server()
    server.connection()
    server.register([Chairo, HealthCheckPlugin], (error) => {

      // EXPECT 2
      expect(error).to.not.exist()

      server.seneca.act({
        role: 'upload',
        cmd: 'healthCheck',
      }, (err, result) => {

        expect(err).to.not.exist()
        // EXPECT 1
        expect(result.ready).to.be.true()
        done()

      })

    })

  })


})

```

As is, those tests above pass successfully.

If I change this line in the second test (at `EXPECT 1`),
```js
expect(result.ready).to.be.false()
```

It times out with this error:
```
  .x

Failed tests:

  2) healthCheck returns ready:true:

      Timed out (2000ms) - healthCheck returns ready:true
```

However, if instead I change this line in the second test (at `EXPECT 2`), outside of the seneca act handler,
```js
expect(error).to.exist()
```

I get the beautifully specific error message and the line indicator:
```
  .x

Failed tests:

  2) healthCheck returns ready:true:

      Expected undefined to exist

      at server.register (/Users/tribou/dev/test/healthCheck_test.js:45:136
```

**Comment by gaboAcosta** [comment]
Hi guys, any news on this? It's rather frustrating to have to be console logging for debug with this happening

**Comment by geek** [comment]
It looks like an issue in seneca, where the exception is trapped in the `act` handler.

**Comment by tribou** [comment]
I think I found a fix [over at the seneca repo](https://github.com/senecajs/seneca/issues/507#issuecomment-242445254)...

If you pass the `done` callback to the `server.seneca.error()` handler, it will throw the nice error messages back to lab as expected:

```js
  it('returns ready:true', (done) => {

    const server = new Hapi.Server()
    server.connection()
    server.register([Chairo, HealthCheckPlugin], (error) => {

      expect(error).to.not.exist()
      server.seneca.error(done)

      server.seneca.act({
        role: 'upload',
        cmd: 'healthCheck',
      }, (err, result) => {

        // if err is used, it will always throw
        // therefore, the following line is no longer needed
        // expect(err).to.not.exist()
        expect(result.ready).to.be.true()
        done()

      })

    })

  })
```

An important note, the second `expect(err).to.not.exist()` is no longer needed in this scenario because the `err` param in the `seneca.act()` handler will always throw if anything is passed through it.  Consequently, anyone who reads this should note it is important to [design your seneca business logic error handling to use the `result` param](https://github.com/senecajs/seneca/issues/574#issuecomment-254540031) to avoid testing issues (trying to assert against the `err` param).

For more details, discussion on the future error-handling architecture of seneca is happening on senecajs/seneca#398.
