### ISSUE TITLE
user defined generateKey method for server.action

### ISSUE THREAD

**Issue by ooogway** [hapijs/chairo#6]
Current implementation of `server.action` method has an inbuilt generateKey function which does not allow complex objects as a part of message getting passed to seneca service. 

https://github.com/hapijs/chairo/blob/master/lib/index.js#L76 

In my implementation, I had to fall back upon server.cache method, with handler calling seneca service and a custom generateKey method.

Wouldn't it be a good idea to allow a user to set custom generateKey function in options for `server.action` to handle such cases? In case it is not defined, we can fallback to a default generateKey function, as currently implemented.

**Comment by zardoz** [comment]
Hi all did this ever get added to the latest master? Currently using Hapi, Chairo with Glue. Would be great if this was there.

**Comment by ooogway** [comment]
since it is a breaking change (options schema moves one level higher up), I think it will take some time to get implemented.

**Comment by geek** [comment]
@zardoz definitely open to a PR, otherwise it will likely be a day before I can get to it.

**Comment by zardoz** [comment]
+1 to that.

**Comment by geek** [comment]
#18 will resolve this

**Comment by zardoz** [comment]
Thanks for the resolution Wyatt, will looks great!
