### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by afgallo** [hapijs/chairo#65]
Hi All,

Thanks for your work on this plugin.

My Seneca microservices live outside of the scope of hapi (which is my API gateway), meaning I use chairo to register Seneca as a client only. I want to write unit tests for scenarios where my microservices may be down. How should I approach this when testing my API gateway?

Many thanks!

**Comment by geek** [comment]
One possibility is to write tests that attempt to connect to non-existent microservice addresses. You can also try writing dummy services in your tests that destroy the socket after there is a connection. The simplest approach is to have tests that try to connect to a localhost port that isn't open, pretending that those are the downed microservices.

**Comment by afgallo** [comment]
Hi @geek thanks for your reply. I really wanted my unit tests to be network independent so I was thinking about registering chairo as a plugin if my environment is DEV, PROD, etc and maybe register a mock plugin for my TEST environment. Does that sound reasonable ?

**Comment by afgallo** [comment]
FYI - just finished implementing the approach I mentioned above and it works perfectly 👌
