### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by hueniverse** [hapijs/chairo#66]
This module is not really useful anymore. I don't see much adoption of seneca or crossover between the two framework. Unless someone really wants to keep it and wants to migrate it to hapi v17, I'll just deprecate it.

**Comment by wzrdtales** [comment]
We're using the module currently, but actually we mostly just use the published instance of seneca which is really a small subset of the functionalities covered by this module. As this runs in production environmens I might come back to this as soon as we start to migrate over applications to hapi v17 and look to spend time on this.
